import { Article, MarketInstrument, RegionRisk, Region, Topic } from './types';

// Curated high-quality seed data — strictly geopolitics, conflicts, wars, diplomacy, macro markets, energy, trade, defense.
export const seedArticles: Article[] = [
  // === GEOPOLITICS: Ukraine / Russia ===
  {
    id: 'a1',
    title: "Russia Launches Largest Drone Barrage on Ukrainian Energy Grid in Six Months",
    summary: "Moscow deployed over 140 drones and missiles overnight targeting thermal power plants and substations across four regions. Ukrainian air defenses claimed a 78% intercept rate.",
    body: "Russian forces conducted a major combined arms strike against Ukraine's energy infrastructure overnight, launching approximately 144 drones and at least 12 cruise missiles. Multiple thermal power plants in Dnipropetrovsk, Kharkiv, and Vinnytsia were hit. Ukrainian authorities reported rolling blackouts affecting 1.4 million households. The attack comes days after Ukraine struck two Russian oil refineries deep inside the country using long-range drones. European gas prices jumped 7% on the news amid fears of further supply disruption this winter.",
    source: "Reuters",
    url: "https://www.reuters.com/world/europe/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Energy & Oil", "Defense & Security", "Conflict Zones"],
    impact: "High",
  },
  {
    id: 'a2',
    title: "NATO Allies Agree to Accelerate Long-Range Strike Deliveries to Kyiv",
    summary: "At an emergency meeting in Brussels, defense ministers approved expedited transfers of ATACMS and Storm Shadow equivalents. Germany and France signaled willingness to increase Taurus and SCALP stockpiles.",
    body: "NATO defense ministers reached a consensus on accelerating long-range precision strike capabilities to Ukraine. The package includes additional ATACMS from the United States and expanded Storm Shadow/SCALP deliveries. Sources indicate Germany is reconsidering its previous refusal to supply Taurus missiles. The decision follows weeks of Russian advances in Donetsk and increased use of glide bombs. Analysts say the move significantly raises escalation risks but could blunt Russia's current momentum.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 71).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Defense & Security", "Diplomacy"],
    impact: "High",
  },
  // === MIDDLE EAST ===
  {
    id: 'a3',
    title: "Houthi Forces Strike Two More Tankers in Red Sea; Insurance Rates Surge 240%",
    summary: "The attacks on Greek and Liberian-flagged vessels mark the most intense week of maritime strikes since January. Major shipping lines are rerouting around the Cape of Good Hope at scale.",
    body: "Yemen's Houthis claimed responsibility for attacks on two additional commercial vessels in the southern Red Sea using anti-ship ballistic missiles and explosive drone boats. Both ships sustained significant damage but no fatalities were reported. The surge has pushed war risk premiums for Red Sea transits above 2.4% of hull value — a 240% increase since October. Maersk and MSC have confirmed all Asia-Europe sailings will continue routing via the Cape for the foreseeable future, adding 10-14 days and roughly $1,200 per container in costs.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 29).toISOString(),
    category: "geopolitics",
    regions: ["Middle East", "Global"],
    topics: ["Shipping & Logistics", "Energy & Oil", "Conflict Zones"],
    impact: "High",
  },
  {
    id: 'a4',
    title: "Israel Strikes Hezbollah Command Centers in Beirut Suburbs; Lebanon Reports 47 Dead",
    summary: "The Israeli Air Force conducted precision strikes on underground facilities in Dahiyeh. Hezbollah vowed 'unprecedented retaliation' while the Lebanese government called for an emergency Arab League session.",
    body: "Israeli fighter jets struck multiple Hezbollah command and control nodes in the southern suburbs of Beirut overnight. The IDF claims the targets included senior operational planners and missile storage sites embedded in civilian areas. Lebanese health authorities put the death toll at 47 with over 180 wounded. The escalation risks drawing in Iran more directly. Oil markets are pricing in a 12% probability of a wider regional war within 30 days according to options data.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 52).toISOString(),
    category: "geopolitics",
    regions: ["Middle East"],
    topics: ["Defense & Security", "Conflict Zones"],
    impact: "High",
  },
  {
    id: 'a5',
    title: "Iran Signals Readiness to Enrich Uranium to 90% if Nuclear Talks Collapse",
    summary: "In a televised address, Iran's atomic chief said the country has completed all technical preparations for weapons-grade enrichment. Western diplomats described the statement as the most direct threat yet.",
    body: "Iran's head of the Atomic Energy Organization warned that if sanctions relief and sanctions-lifting commitments from the 2015 nuclear deal are not honored, Iran will move immediately to 90% enrichment. Current stockpiles of 60% enriched uranium are estimated at 165kg — enough for several bombs if further enriched. The IAEA has expressed 'grave concern' and called for urgent high-level talks in Vienna.",
    source: "The Guardian",
    url: "https://www.theguardian.com/world",
    publishedAt: new Date(Date.now() - 1000 * 60 * 89).toISOString(),
    category: "geopolitics",
    regions: ["Middle East", "Global"],
    topics: ["Sanctions", "Diplomacy", "Technology & Export Controls"],
    impact: "High",
  },
  // === ASIA-PACIFIC / CHINA ===
  {
    id: 'a6',
    title: "China Conducts Large-Scale Joint Exercises Around Taiwan; Taipei Scrambles Jets",
    summary: "The PLA Eastern Theater Command launched its largest simulated blockade drills in 18 months involving 42 warships, 58 aircraft, and live-fire missile launches east of the island.",
    body: "Beijing launched extensive military exercises around Taiwan in response to recent US congressional visits and new arms packages. The drills included simulated missile strikes on ports, a full encirclement of the island, and anti-submarine warfare practice. Taiwan's Ministry of National Defense reported 58 PLA aircraft entered its ADIZ. Semiconductor stocks in Taipei fell 3.8% on the news. TSMC said contingency plans remain active.",
    source: "Nikkei Asia",
    url: "https://asia.nikkei.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    category: "geopolitics",
    regions: ["Asia-Pacific"],
    topics: ["Defense & Security", "Conflict Zones", "Technology & Export Controls"],
    impact: "High",
  },
  {
    id: 'a7',
    title: "US Imposes New Export Controls on Advanced AI Chips to China and Middle East Entities",
    summary: "The Commerce Department added 28 Chinese firms and several UAE-based entities to the Entity List, tightening controls on NVIDIA H100/H200 and AMD MI300 series GPUs.",
    body: "The Biden administration expanded restrictions on advanced semiconductors and manufacturing equipment to China. The new rules target companies acquiring chips for military AI applications and also hit several Gulf entities suspected of transshipment. NVIDIA shares fell 4.2% in after-hours trading. Beijing condemned the move as 'economic coercion' and vowed countermeasures. Analysts expect retaliatory restrictions on rare earth magnet exports.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 67).toISOString(),
    category: "geopolitics",
    regions: ["Asia-Pacific", "Americas", "Global"],
    topics: ["Technology & Export Controls", "Trade & Tariffs", "Sanctions"],
    impact: "High",
  },
  {
    id: 'a8',
    title: "Philippines and Japan Formalize Reciprocal Access Agreement; China Warns of 'Consequences'",
    summary: "Manila and Tokyo signed a landmark defense pact allowing mutual troop deployments. The agreement significantly expands the US-Japan-Philippines security triangle in the South China Sea.",
    body: "The Philippines and Japan signed a Reciprocal Access Agreement enabling joint training, disaster response, and rotational deployments. The pact is widely viewed as a direct response to increased Chinese coast guard activity around Second Thomas Shoal. Beijing issued a sharp diplomatic protest, accusing the three countries of forming an 'Asian NATO'. Regional analysts say the agreement marks the clearest sign yet of Southeast Asian hedging against Chinese maritime expansion.",
    source: "South China Morning Post",
    url: "https://www.scmp.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 103).toISOString(),
    category: "geopolitics",
    regions: ["Asia-Pacific"],
    topics: ["Defense & Security", "Diplomacy"],
    impact: "Medium",
  },
  // === AFRICA ===
  {
    id: 'a9',
    title: "Sudan's RSF Captures Key Oil Facilities in Kordofan; UAE and Egypt Trade Accusations",
    summary: "The Rapid Support Forces seized the Heglig and Neem oil fields, cutting roughly 40% of Sudan's remaining crude output. Both Egypt and the UAE have been accused by the other of direct support to rival factions.",
    body: "Sudan's civil war entered a dangerous new phase after the RSF captured major oil infrastructure in West Kordofan. Production at the seized fields has halted. The move threatens to deepen the humanitarian crisis and further destabilize the broader Sahel. Egypt, which supports the Sudanese Armed Forces, accused the UAE of arming the RSF via Chad and Libya. Abu Dhabi denied the claims. Brent crude gained $1.80 on supply concerns.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    category: "geopolitics",
    regions: ["Africa", "Middle East"],
    topics: ["Energy & Oil", "Conflict Zones"],
    impact: "Medium",
  },
  {
    id: 'a10',
    title: "Wagner Successor Africa Corps Expands Footprint in Burkina Faso and Mali Gold Mines",
    summary: "New satellite imagery and local reporting show Russian personnel securing major gold operations previously controlled by the Malian junta. Production is reportedly being diverted to fund operations.",
    body: "The Africa Corps, successor to the Wagner Group, has significantly expanded control over artisanal and industrial gold mining operations in northern Mali and western Burkina Faso. Locals report forced labor and direct Russian management at several sites. The gold is believed to be smelted and flown out via private aircraft to finance the group's activities across the Sahel. France and the US have both raised the issue at the UN Security Council.",
    source: "Le Monde",
    url: "https://www.lemonde.fr/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 128).toISOString(),
    category: "geopolitics",
    regions: ["Africa"],
    topics: ["Conflict Zones", "Commodities"],
    impact: "Medium",
  },
  // === MARKETS: ENERGY & COMMODITIES ===
  {
    id: 'a11',
    title: "OPEC+ Extends Deep Production Cuts Through Q3 2026 as Demand Outlook Weakens",
    summary: "The group agreed to maintain 2.2 million barrels per day of voluntary cuts. Saudi Arabia signaled it would not increase output until global inventories fall further.",
    body: "OPEC+ ministers decided to extend the deepest tranche of production cuts through at least September 2026. The decision came after internal modeling showed global oil demand growth could slow to just 1.1 million bpd next year. Brent crude traded at $79.40 after the announcement. Traders noted that Saudi Arabia's insistence on compliance from other members suggests the Kingdom is willing to sacrifice market share to defend prices near $80.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 49).toISOString(),
    category: "markets",
    regions: ["Middle East", "Global"],
    topics: ["Energy & Oil", "Commodities"],
    impact: "High",
  },
  {
    id: 'a12',
    title: "Copper Hits Record High on Massive Chinese Strategic Stockpile Purchases and Supply Disruption",
    summary: "LME copper surged past $11,800 per tonne after reports that China's State Reserve Bureau bought 300,000 tonnes and major Chilean and Peruvian mines face labor and permitting delays.",
    body: "Copper reached an all-time nominal high above $11,850/t amid a perfect storm of Chinese strategic buying and structural supply issues in Latin America. The State Reserve Bureau's massive purchases are widely interpreted as preparation for grid and EV manufacturing expansion. At the same time, Codelco and several large Peruvian operations are struggling with grade declines and social license problems. Goldman Sachs raised its 2026 average forecast to $13,200.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 36).toISOString(),
    category: "markets",
    regions: ["Asia-Pacific", "Americas", "Global"],
    topics: ["Commodities", "Supply Chains"],
    impact: "High",
  },
  {
    id: 'a13',
    title: "European Natural Gas Prices Spike 11% as Norwegian Maintenance Overruns and Ukraine Transit Uncertainty Grow",
    summary: "TTF benchmark gas jumped to €42/MWh. Traders are pricing in the very real possibility that the Ukraine transit agreement will not be renewed before year end.",
    body: "European benchmark natural gas prices surged after Equinor reported that planned maintenance at key North Sea fields would last longer than expected. At the same time, Ukrainian officials indicated they are unlikely to extend the current Russian transit agreement beyond December 31. European storage is currently at 94% but winter demand and potential LNG competition from Asia are creating a tense forward curve. German industrial users are already locking in higher hedges.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 61).toISOString(),
    category: "markets",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Energy & Oil", "Commodities"],
    impact: "Medium",
  },
  // === MARKETS: EQUITIES / MACRO ===
  {
    id: 'a14',
    title: "Fed Minutes Reveal Deep Divisions Over Pace of Rate Cuts Amid Geopolitical Uncertainty",
    summary: "Several FOMC members expressed concern that escalating Middle East tensions and potential new tariffs could complicate the inflation trajectory. Markets now price only two 25bp cuts for 2025.",
    body: "The latest FOMC minutes showed a split between officials eager to continue normalizing policy and those worried that geopolitical risks — particularly energy price spikes and new trade barriers — could re-ignite inflation. Several participants highlighted that core services inflation remains sticky. Treasury yields rose sharply after the release. The dollar index strengthened to its highest level since July.",
    source: "CNBC",
    url: "https://www.cnbc.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 82).toISOString(),
    category: "markets",
    regions: ["Americas", "Global"],
    topics: ["Central Banks & Policy", "Equities & Indices"],
    impact: "High",
  },
  {
    id: 'a15',
    title: "Defense Stocks Rally as European NATO Members Commit to 2.5% GDP Spending Floor by 2027",
    summary: "Rheinmetall, BAE Systems, and Leonardo rose between 4-8%. The commitment is the most concrete signal yet that Europe is structurally increasing defense outlays for the long term.",
    body: "European defense contractors surged after 11 NATO members jointly pledged to raise minimum defense spending to 2.5% of GDP by 2027, with several signaling 3% ambitions. The move follows years of underinvestment and is expected to generate sustained multi-year procurement pipelines. Rheinmetall confirmed it is expanding artillery shell capacity by another 40%. Analysts at Jefferies called it a 'structural re-rating' for the sector.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    category: "markets",
    regions: ["Europe"],
    topics: ["Defense & Security", "Equities & Indices"],
    impact: "Medium",
  },
  // === MORE DIVERSE COVERAGE ===
  {
    id: 'a16',
    title: "India and China Complete Disengagement at Depsang Plains; Border Trade to Partially Resume",
    summary: "After 18 months of negotiations, the two sides have agreed to pull back forces from the last major friction point in eastern Ladakh. Limited border trade through Nathu La is expected to restart within weeks.",
    body: "India and China have finalized disengagement at Depsang, the final major contested area in Ladakh. Both armies will withdraw to pre-2020 positions over the next 10 days under a verified monitoring mechanism. While full normalization remains distant, the move is expected to reduce the risk of accidental escalation. Indian officials said limited trade through the Nathu La pass will resume on a trial basis. Defense stocks in India eased on the news.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 94).toISOString(),
    category: "geopolitics",
    regions: ["Asia-Pacific"],
    topics: ["Diplomacy", "Conflict Zones"],
    impact: "Medium",
  },
  {
    id: 'a17',
    title: "Venezuela Seizes Chevron Assets as US Sanctions Deadline Expires Without Deal",
    summary: "Caracas nationalized several Chevron-operated fields after Washington refused to extend limited sanctions relief. Oil production from the assets has already begun declining sharply.",
    body: "The Venezuelan government took control of Chevron's remaining producing assets after the US Treasury declined to renew a narrow sanctions waiver. Production from the fields has reportedly dropped over 18% in the past month as technical expertise and spare parts became unavailable. Chevron said it was exploring all legal options. Brent crude was little changed as the volumes involved are relatively small in the global context.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 117).toISOString(),
    category: "geopolitics",
    regions: ["Americas"],
    topics: ["Energy & Oil", "Sanctions"],
    impact: "Medium",
  },
  {
    id: 'a18',
    title: "EU Finalizes Carbon Border Adjustment Mechanism; China and India Threaten WTO Action",
    summary: "The definitive CBAM rules were published in the Official Journal. Importers of steel, aluminum, cement, and fertilizers will begin paying carbon tariffs from 2026. Major exporters are preparing retaliation.",
    body: "The European Union published the final implementing rules for the Carbon Border Adjustment Mechanism. From January 2026, importers will have to surrender CBAM certificates corresponding to the embedded emissions of covered goods. China called the measure 'protectionism disguised as climate policy' and said it would challenge the mechanism at the WTO alongside India and several other nations. European steelmakers welcomed the move as essential for competitiveness.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 133).toISOString(),
    category: "markets",
    regions: ["Europe", "Asia-Pacific", "Global"],
    topics: ["Trade & Tariffs", "Commodities"],
    impact: "Medium",
  },
  {
    id: 'a19',
    title: "Yen Weakens to 158 Against Dollar as BOJ Signals Patience on Further Rate Hikes",
    summary: "The Bank of Japan left policy unchanged and downplayed near-term tightening. The yen's continued slide is raising concerns about imported inflation and the cost of servicing Japan's massive public debt.",
    body: "The yen fell to 158.4 per dollar after the Bank of Japan maintained its ultra-loose stance and Governor Ueda signaled that further rate hikes would depend on sustained wage growth. The move comes as Japan faces renewed pressure on energy import costs due to Middle East tensions. Finance Ministry officials are reportedly monitoring the currency 'very closely'. Several G7 sources expressed concern about disorderly moves.",
    source: "Nikkei Asia",
    url: "https://asia.nikkei.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
    category: "markets",
    regions: ["Asia-Pacific", "Global"],
    topics: ["Central Banks & Policy", "Equities & Indices"],
    impact: "Medium",
  },
  {
    id: 'a20',
    title: "Myanmar Junta Launches Major Offensive in Shan State; China Evacuates Border Workers",
    summary: "Intense fighting between the military and ethnic armed groups near the Chinese border has prompted Beijing to evacuate hundreds of Chinese nationals. Cross-border trade has been suspended.",
    body: "Myanmar's military launched a large-scale operation against the Myanmar National Democratic Alliance Army and other groups in northern Shan State. Heavy artillery and airstrikes were reported near the border town of Muse. China has closed several border crossings and evacuated personnel from industrial zones and mining projects. The conflict is disrupting rare earth and jade supply chains that feed into Chinese manufacturing.",
    source: "South China Morning Post",
    url: "https://www.scmp.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 146).toISOString(),
    category: "geopolitics",
    regions: ["Asia-Pacific"],
    topics: ["Conflict Zones", "Supply Chains"],
    impact: "Medium",
  },
  // Continue with more breadth...
  {
    id: 'a21',
    title: "Saudi Arabia and UAE Deepen Defense Ties With Indonesia in $3.2bn Arms and Training Deal",
    summary: "The agreement includes joint development of drones and missiles plus extensive training programs. Analysts see it as part of a broader strategy to build influence across the Global South.",
    body: "Riyadh and Abu Dhabi signed a major defense cooperation framework with Jakarta covering co-production of UAVs, precision munitions, and a large-scale officer training program. The deal is the largest defense export package ever for either Gulf state to Southeast Asia. It comes as both countries seek to diversify partnerships away from traditional Western suppliers while expanding soft power.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 109).toISOString(),
    category: "geopolitics",
    regions: ["Middle East", "Asia-Pacific"],
    topics: ["Defense & Security", "Diplomacy"],
    impact: "Medium",
  },
  {
    id: 'a22',
    title: "Rare Earth Prices Surge 28% After China Tightens Export Quotas on Heavy Elements",
    summary: "Beijing reduced export quotas for dysprosium and terbium by 40%. The move is widely seen as retaliation for new US chip controls and a strategic effort to retain processing dominance.",
    body: "China slashed export quotas for heavy rare earth elements critical for defense systems, EVs, and wind turbines. Prices for dysprosium oxide jumped 34% in a single session. Western governments have been scrambling to develop non-Chinese supply chains since 2022, but new mines in Australia, the US, and Vietnam will take years to reach meaningful scale. Japanese and Korean magnet makers are the most exposed.",
    source: "Nikkei Asia",
    url: "https://asia.nikkei.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    category: "markets",
    regions: ["Asia-Pacific", "Global"],
    topics: ["Commodities", "Technology & Export Controls", "Supply Chains"],
    impact: "High",
  },
  {
    id: 'a23',
    title: "Turkey Signals It May Block Sweden's NATO Path Over New Kurdish Militant Designations",
    summary: "Ankara is demanding additional Swedish legal changes after a court decision it says was too lenient on PKK-linked figures. The move threatens to further delay Nordic integration into the alliance.",
    body: "Turkish officials indicated they could withhold final ratification of Sweden's NATO accession over what they describe as insufficient action against Kurdish militant financing and propaganda networks. The comments sent ripples through Brussels just weeks after Finland joined. Sweden's government said it had already passed the most extensive counter-terrorism legislation in its history.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 87).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Middle East"],
    topics: ["Diplomacy", "Defense & Security"],
    impact: "Medium",
  },
  {
    id: 'a24',
    title: "Brent-WTI Spread Narrows to 18-Month Low as US Crude Exports Hit Record 5.8 Million Barrels/Day",
    summary: "American crude exports continue to surge, fundamentally altering global arbitrage dynamics. Gulf Coast refiners are running at high utilization while Europe absorbs more US barrels.",
    body: "The transatlantic crude spread has collapsed to just $3.40 as US exports hit another all-time high. American producers are benefiting from strong international demand and a relatively weak dollar. European refiners have increased US crude intake by 38% year-over-year. The trend is pressuring OPEC+ cohesion as some members complain that US supply is undermining price support efforts.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 64).toISOString(),
    category: "markets",
    regions: ["Americas", "Global"],
    topics: ["Energy & Oil", "Commodities"],
    impact: "Medium",
  },
  {
    id: 'a25',
    title: "Pakistan Secures $2.1bn IMF Tranche After Securing Chinese Debt Rollover Assurances",
    summary: "The new Stand-By Arrangement disbursement was approved after Islamabad obtained written commitments from Beijing to roll over $4.8bn in bilateral deposits and loans maturing this year.",
    body: "The IMF Executive Board approved the second review under Pakistan's Stand-By Arrangement, unlocking $2.1 billion. The program was at risk after reserves fell below critical levels. China provided the critical backstop by formally agreeing to roll over deposits at the State Bank of Pakistan. The arrangement gives Pakistan breathing room but analysts warn structural fiscal problems remain severe.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 99).toISOString(),
    category: "markets",
    regions: ["Asia-Pacific", "Middle East"],
    topics: ["Central Banks & Policy", "Diplomacy"],
    impact: "Medium",
  },
  {
    id: 'a26',
    title: "US and EU Launch Joint Critical Minerals 'Buyers Club' to Reduce China Dependence",
    summary: "The new Minerals Security Partnership Finance Network aims to coordinate public and private capital for non-Chinese lithium, nickel, cobalt, and graphite projects. Initial focus is on Africa and Australia.",
    body: "Washington and Brussels formally launched a coordinated financing mechanism under the Minerals Security Partnership. The goal is to mobilize $15-20bn over five years for upstream projects outside China. Initial priority projects include lithium in Zimbabwe and Chile, nickel in Indonesia (non-Chinese controlled), and graphite in Tanzania. Beijing criticized the initiative as an attempt to 'decouple' supply chains.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 121).toISOString(),
    category: "geopolitics",
    regions: ["Americas", "Europe", "Africa", "Global"],
    topics: ["Supply Chains", "Technology & Export Controls", "Commodities"],
    impact: "Medium",
  },
  {
    id: 'a27',
    title: "North Korea Fires Multiple ICBMs Into Sea of Japan; South Korea and Japan Conduct Joint Drills",
    summary: "Pyongyang launched three Hwasong-18 solid-fuel ICBMs in its most significant test of the year. The missiles flew 1,000+ km. Seoul, Tokyo, and Washington held trilateral naval exercises in immediate response.",
    body: "North Korea conducted its largest ICBM test of 2025, launching three solid-propellant Hwasong-18 missiles that reached apogees over 6,000km. All landed in Japan's exclusive economic zone. The test follows weeks of increased artillery fire across the DMZ. South Korea, Japan, and the US responded with large-scale live-fire naval drills. Markets in Seoul fell 2.1%.",
    source: "Nikkei Asia",
    url: "https://asia.nikkei.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 33).toISOString(),
    category: "geopolitics",
    regions: ["Asia-Pacific"],
    topics: ["Defense & Security", "Conflict Zones"],
    impact: "High",
  },
  {
    id: 'a28',
    title: "Gold Surpasses $2,850 as Central Banks Continue Aggressive Buying and Geopolitical Premium Grows",
    summary: "The yellow metal made another record high. The People's Bank of China, RBI, and several Middle Eastern central banks have been consistent buyers. ETF inflows have also accelerated sharply since October.",
    body: "Spot gold pushed above $2,850/oz for the first time, driven by relentless central bank demand and a broad flight-to-safety bid. The PBoC has now added gold for 18 consecutive months. India's RBI is also believed to be accumulating. Physical premiums in Shanghai and Dubai remain elevated. Some analysts now target $3,000 within 12 months if Middle East tensions remain unresolved.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 27).toISOString(),
    category: "markets",
    regions: ["Global"],
    topics: ["Commodities", "Central Banks & Policy"],
    impact: "High",
  },
  {
    id: 'a29',
    title: "EU Parliament Approves New Russia Sanctions Package Targeting Shadow Fleet and Crypto",
    summary: "The 14th package includes measures against 120 vessels in Russia's shadow tanker fleet, several crypto mixers, and additional restrictions on dual-use goods transiting third countries.",
    body: "The European Parliament gave final approval to a sweeping new sanctions package against Russia. Key elements include designation of over 120 tankers believed to be part of the shadow fleet carrying Russian oil above the G7 price cap, sanctions on crypto services used to evade restrictions, and new due diligence requirements for goods exported to Central Asia and the Caucasus. Oil markets were largely unmoved.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 78).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Sanctions", "Energy & Oil"],
    impact: "Medium",
  },
  {
    id: 'a30',
    title: "Brazil and China Agree $8bn Local Currency Trade Settlement Framework, Bypassing Dollar",
    summary: "The new mechanism will allow direct BRL-RMB clearing for bilateral trade in soybeans, iron ore, and manufactured goods. It is the largest such arrangement Beijing has signed with a major commodity exporter.",
    body: "Brazil and China finalized a bilateral local currency settlement system expected to cover up to 30% of their $150bn annual trade within two years. The deal reduces reliance on the dollar for the world's largest soybean and iron ore trade flows. Brazilian officials described it as 'strategic diversification'. The yuan has been gaining modest ground in Brazil's FX reserves.",
    source: "South China Morning Post",
    url: "https://www.scmp.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 114).toISOString(),
    category: "markets",
    regions: ["Americas", "Asia-Pacific"],
    topics: ["Trade & Tariffs", "Central Banks & Policy"],
    impact: "Medium",
  },
];

export const initialMarketData: MarketInstrument[] = [
  { symbol: "SPX", name: "S&P 500", price: 5984.2, change: 0.31, type: "index", history: [5942, 5951, 5948, 5963, 5971, 5968, 5979, 5988, 5982, 5987, 5991, 5984] },
  { symbol: "NDX", name: "Nasdaq 100", price: 21340, change: -0.84, type: "index", history: [21580, 21540, 21490, 21510, 21460, 21420, 21390, 21450, 21380, 21310, 21290, 21340] },
  { symbol: "UKX", name: "FTSE 100", price: 8241, change: 0.47, type: "index", history: [8190, 8205, 8198, 8212, 8224, 8219, 8231, 8238, 8245, 8237, 8249, 8241] },
  { symbol: "NKY", name: "Nikkei 225", price: 39870, change: -1.12, type: "index", history: [40650, 40520, 40410, 40380, 40290, 40180, 40050, 39980, 40040, 39920, 39840, 39870] },
  { symbol: "DAX", name: "DAX", price: 19280, change: 0.68, type: "index", history: [19040, 19090, 19120, 19150, 19180, 19160, 19210, 19240, 19270, 19250, 19290, 19280] },
  { symbol: "CL", name: "WTI Crude", price: 76.84, change: 1.9, type: "commodity", history: [74.8, 75.1, 75.4, 75.2, 75.6, 75.9, 76.1, 76.3, 76.5, 76.4, 76.7, 76.84] },
  { symbol: "GC", name: "Gold", price: 2854.6, change: 0.92, type: "commodity", history: [2812, 2819, 2824, 2829, 2835, 2838, 2841, 2845, 2849, 2851, 2853, 2854.6] },
  { symbol: "USDCNY", name: "USD/CNY", price: 7.142, change: 0.11, type: "fx", history: [7.128, 7.131, 7.135, 7.138, 7.141, 7.139, 7.143, 7.147, 7.144, 7.149, 7.146, 7.142] },
];

export const initialRegionRisk: RegionRisk[] = [
  { region: "Middle East", level: "High", score: 84, storyCount: 9 },
  { region: "Asia-Pacific", level: "Elevated", score: 67, storyCount: 8 },
  { region: "Europe", level: "Elevated", score: 61, storyCount: 7 },
  { region: "Russia & Central Asia", level: "Elevated", score: 58, storyCount: 5 },
  { region: "Africa", level: "Moderate", score: 44, storyCount: 4 },
  { region: "Americas", level: "Moderate", score: 39, storyCount: 6 },
  { region: "Global", level: "Moderate", score: 52, storyCount: 11 },
];

// Plausible new story templates for live injection
export const storyTemplates: Omit<Article, 'id' | 'publishedAt'>[] = [
  {
    title: "EU Defense Ministers Approve Joint Procurement of 1,000 Long-Range Strike Munitions",
    summary: "The decision marks the first major pooled procurement program under the new European Defense Industrial Strategy.",
    body: "European defense ministers have greenlit a landmark joint procurement initiative for precision-guided munitions. The program will deliver over 1,000 deep-strike weapons to member states by 2027 with common specifications. Industry sources say the contract is likely to be split between MBDA and a German-French consortium. The move is designed to reduce reliance on US supply chains for critical munitions.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    category: "geopolitics",
    regions: ["Europe"],
    topics: ["Defense & Security", "Diplomacy"],
    impact: "High",
  },
  {
    title: "China's Shadow Fleet Adds 14 VLCCs in Three Months, Undermining Price Cap Enforcement",
    summary: "New AIS data shows a rapid expansion of opaque tankers transferring Russian crude with ship-to-ship operations in the South China Sea.",
    body: "China-linked entities have added at least 14 very large crude carriers to the shadow fleet over the past quarter. These vessels frequently engage in ship-to-ship transfers and disable AIS transponders. The development is complicating Western efforts to enforce the G7 oil price cap. Several of the ships were previously on Western insurance registries and have since reflagged to Gabon and the Comoros.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    category: "markets",
    regions: ["Asia-Pacific", "Russia & Central Asia", "Global"],
    topics: ["Energy & Oil", "Sanctions", "Shipping & Logistics"],
    impact: "Medium",
  },
  {
    title: "Israel-Hamas Ceasefire Talks in Doha Collapse Over Hostage and Withdrawal Sequencing",
    summary: "The latest round of indirect negotiations ended without progress. Both sides accused the other of maximalist demands that made compromise impossible.",
    body: "Qatari-mediated talks between Israel and Hamas broke down after 11 days. The core dispute remains the sequencing of hostage releases versus Israeli withdrawal from Gaza. Egyptian and Qatari mediators said the gap had actually widened. Markets reacted with a modest risk-off move in regional equities and a small bid for gold and the dollar.",
    source: "Al Jazeera",
    url: "https://www.aljazeera.com/",
    category: "geopolitics",
    regions: ["Middle East"],
    topics: ["Conflict Zones", "Diplomacy"],
    impact: "High",
  },
  {
    title: "South Korea Unveils $14bn Package to Secure Critical Minerals in Australia and Canada",
    summary: "Seoul is making its largest-ever overseas resource investment push to secure lithium, nickel, and rare earths outside Chinese control.",
    body: "The South Korean government and state-owned resource companies announced a $14 billion investment program targeting battery and magnet metals in stable jurisdictions. The package includes equity stakes in major Australian lithium and Canadian nickel projects plus offtake agreements. Officials described the program as 'existential' for Korea's EV and semiconductor supply chains.",
    source: "Nikkei Asia",
    url: "https://asia.nikkei.com/",
    category: "markets",
    regions: ["Asia-Pacific", "Global"],
    topics: ["Commodities", "Supply Chains"],
    impact: "Medium",
  },
];
