import { Article, MarketInstrument, RegionRisk, Region, Topic } from './types';

// Curated high-quality seed data — refreshed with current (June 2026) geopolitics & markets focus.
// All publishedAt values are calculated relative to now so they always feel fresh.
export const seedArticles: Article[] = [
  // === ISRAEL-IRAN DIRECT CONFLICT (dominant current story) ===
  {
    id: 'a1',
    title: "Israel Launches Fresh Strikes on Iranian Nuclear and Military Sites; Tehran Fires Missiles in Retaliation",
    summary: "Israeli jets hit multiple targets inside Iran including nuclear facilities. Iran responded with ballistic missile barrages toward Israel. US forces on high alert across the region.",
    body: "Israel conducted a new wave of precision airstrikes against Iranian nuclear infrastructure and IRGC sites early today. Iranian state media confirmed missile launches toward Israeli territory in the first direct bombardment since the fragile ceasefire. The US has deployed additional air defenses to the Gulf and warned of further escalation. Oil markets are pricing in significant risk to the Strait of Hormuz.",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
    category: "geopolitics",
    regions: ["Middle East", "Global"],
    topics: ["Defense & Security", "Conflict Zones", "Energy & Oil"],
    impact: "High",
  },
  {
    id: 'a2',
    title: "Trump Says US 'Will Strike Iran Very Hard' if No Deal Within Days as Oil Spikes",
    summary: "President Trump issued a sharp deadline for Iran talks while US forces reportedly completed additional strikes. Brent crude jumped above $106 amid fears of Hormuz disruption.",
    body: "In a series of statements, President Trump said the US would hit Iran 'very hard' unless a comprehensive deal is reached quickly. Markets reacted with sharp oil gains and equity volatility. Shipping companies are already rerouting tankers away from the Persian Gulf. Analysts warn that even a partial closure of the Strait of Hormuz could push prices well above $120.",
    source: "CNBC",
    url: "https://www.cnbc.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    category: "geopolitics",
    regions: ["Middle East", "Americas", "Global"],
    topics: ["Conflict Zones", "Energy & Oil", "Diplomacy"],
    impact: "High",
  },
  {
    id: 'a3',
    title: "Iran Ceasefire Hopes Trigger Massive Relief Rally; Oil Plunges 11-14% in Hours",
    summary: "White House signals possible two-week ceasefire. Markets surged with S&P 500 up over 2.5% while Brent and WTI crude cratered on hopes the Strait of Hormuz may reopen.",
    body: "Reports of a potential short-term US-Iran ceasefire triggered the biggest one-day equity rally in months. Oil futures collapsed, with WTI briefly down nearly 14%. Some commercial vessels have already begun transiting the Strait again. Traders remain cautious, noting the ceasefire is fragile and could collapse quickly.",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    category: "markets",
    regions: ["Middle East", "Global"],
    topics: ["Energy & Oil", "Equities & Indices"],
    impact: "High",
  },
  // === UKRAINE / RUSSIA ongoing ===
  {
    id: 'a4',
    title: "Ukraine Strikes Deep Into Russia, Hitting Major Energy and Military Targets",
    summary: "Kyiv launched long-range drone and missile attacks on Russian oil refineries and air bases. Moscow responded with heavy strikes on Ukrainian infrastructure.",
    body: "Ukrainian forces conducted one of their deepest strikes of the war, targeting energy facilities and military airfields hundreds of kilometers inside Russia. Several refineries reported fires. Russia retaliated with large-scale missile and drone barrages against Ukrainian energy and cities. European gas prices ticked higher on supply concerns.",
    source: "AP News",
    url: "https://apnews.com/hub/war-and-unrest",
    publishedAt: new Date(Date.now() - 1000 * 60 * 81).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Energy & Oil", "Defense & Security", "Conflict Zones"],
    impact: "High",
  },
  {
    id: 'a5',
    title: "Russia Kills 10 Including Children in New Missile Strike on Ukrainian City",
    summary: "A Russian ballistic missile hit a residential area in a major Ukrainian city. European leaders condemned the attack and renewed calls for more air defense systems.",
    body: "Russian forces struck a Ukrainian city with a new type of missile, killing at least 10 people including children. The attack comes amid stalled peace efforts and increased Western weapons deliveries. NATO members are accelerating additional Patriot and SAMP/T systems to Ukraine.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 19).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Defense & Security", "Conflict Zones"],
    impact: "High",
  },
  // === BROADER IMPACTS ===
  {
    id: 'a6',
    title: "Oil Prices Remain Elevated Above $106 as Iran Conflict Drags and Hormuz Risk Persists",
    summary: "Brent crude is holding above $106-$107 per barrel. Traders are watching any sign that the Strait of Hormuz could be fully or partially closed.",
    body: "Despite occasional relief rallies on ceasefire rumors, oil remains structurally elevated due to the Iran conflict. Physical market participants are paying large premiums for prompt barrels. European and Asian refiners are scrambling for alternative crudes. Goldman and other banks have raised their near-term forecasts.",
    source: "CNBC",
    url: "https://www.cnbc.com/oil/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 34).toISOString(),
    category: "markets",
    regions: ["Middle East", "Global"],
    topics: ["Energy & Oil", "Commodities"],
    impact: "High",
  },
  {
    id: 'a7',
    title: "S&P 500 and Nasdaq Swing Wildly on Iran Headlines; VIX Spikes Above 21",
    summary: "US equities have seen massive intraday moves tied to every Trump and Iran statement. Volatility has jumped sharply as investors price geopolitical risk.",
    body: "The S&P 500 and Nasdaq have experienced some of the largest daily ranges of the year as headlines from the Middle East swing sentiment. The VIX has climbed back above 21. Defense and energy names are outperforming while growth stocks are under pressure.",
    source: "CNN Business",
    url: "https://www.cnn.com/markets",
    publishedAt: new Date(Date.now() - 1000 * 60 * 51).toISOString(),
    category: "markets",
    regions: ["Americas", "Global"],
    topics: ["Equities & Indices"],
    impact: "High",
  },
  // === OTHER REGIONS / ONGOING ===
  {
    id: 'a8',
    title: "China and EU Edge Closer to Trade War Over EV Tariffs and Steel",
    summary: "Brussels is preparing new tariffs on Chinese electric vehicles and steel. Beijing has warned of strong countermeasures including restrictions on critical minerals.",
    body: "The EU is moving toward final tariffs on Chinese EVs and is investigating steel subsidies. China has signaled it may restrict exports of rare earths and other materials critical to European industry. Markets are watching for any impact on global supply chains.",
    source: "Financial Times",
    url: "https://www.ft.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 73).toISOString(),
    category: "geopolitics",
    regions: ["Europe", "Asia-Pacific", "Global"],
    topics: ["Trade & Tariffs", "Technology & Export Controls"],
    impact: "Medium",
  },
  {
    id: 'a9',
    title: "Houthi Attacks Continue in Red Sea Despite Iran Focus; Insurance Rates Stay Elevated",
    summary: "Yemen's Houthis claimed another attack on commercial shipping. Major lines continue routing around Africa as war risk premiums remain extremely high.",
    body: "Even as attention shifts to the Iran-Israel front, Houthi forces continue targeting vessels in the Red Sea and Gulf of Aden. Several major container and tanker operators have said they will keep using the Cape of Good Hope route for the foreseeable future.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
    category: "geopolitics",
    regions: ["Middle East", "Global"],
    topics: ["Shipping & Logistics", "Conflict Zones"],
    impact: "Medium",
  },
  {
    id: 'a10',
    title: "Gold Holds Near Record Highs as Central Banks Buy and Geopolitical Premium Persists",
    summary: "Spot gold remains close to all-time highs above $2,800-$2,850. Central bank buying from China, India and others continues unabated.",
    body: "Gold is benefiting from both safe-haven demand tied to the Middle East conflict and relentless central bank accumulation. The PBoC and RBI have been consistent buyers. ETF inflows have also accelerated. Some analysts now see $3,000 as a realistic target if tensions remain elevated.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 29).toISOString(),
    category: "markets",
    regions: ["Global"],
    topics: ["Commodities", "Central Banks & Policy"],
    impact: "High",
  },
];

// Realistic current market starting points (June 2026 context) — simulation will drift from here.
export const initialMarketData: MarketInstrument[] = [
  { symbol: "SPX", name: "S&P 500", price: 7267, change: -1.62, type: "index", history: [7383, 7366, 7341, 7318, 7295, 7288, 7274, 7268, 7279, 7265, 7258, 7267] },
  { symbol: "NDX", name: "Nasdaq 100", price: 25169, change: -1.98, type: "index", history: [25678, 25590, 25480, 25340, 25290, 25210, 25180, 25140, 25190, 25150, 25120, 25169] },
  { symbol: "UKX", name: "FTSE 100", price: 8240, change: 0.4, type: "index", history: [8210, 8220, 8215, 8230, 8238, 8245, 8239, 8248, 8242, 8251, 8246, 8240] },
  { symbol: "NKY", name: "Nikkei 225", price: 38500, change: -0.8, type: "index", history: [38950, 38820, 38710, 38640, 38580, 38520, 38490, 38530, 38480, 38510, 38470, 38500] },
  { symbol: "DAX", name: "DAX", price: 18350, change: 0.55, type: "index", history: [18220, 18260, 18290, 18310, 18340, 18320, 18360, 18380, 18350, 18370, 18390, 18350] },
  { symbol: "CL", name: "WTI Crude", price: 92.2, change: 2.41, type: "commodity", history: [89.5, 90.1, 90.8, 91.2, 91.7, 91.4, 91.9, 92.3, 92.1, 92.5, 92.0, 92.2] },
  { symbol: "GC", name: "Gold", price: 2685, change: 0.65, type: "commodity", history: [2660, 2665, 2670, 2674, 2679, 2682, 2684, 2687, 2683, 2688, 2686, 2685] },
  { symbol: "USDCNY", name: "USD/CNY", price: 7.245, change: -0.12, type: "fx", history: [7.258, 7.252, 7.249, 7.255, 7.248, 7.251, 7.247, 7.243, 7.239, 7.241, 7.244, 7.245] },
];

export const initialRegionRisk: RegionRisk[] = [
  { region: "Middle East", level: "High", score: 91, storyCount: 12 },
  { region: "Europe", level: "Elevated", score: 64, storyCount: 6 },
  { region: "Asia-Pacific", level: "Elevated", score: 58, storyCount: 5 },
  { region: "Russia & Central Asia", level: "Elevated", score: 61, storyCount: 4 },
  { region: "Global", level: "Elevated", score: 72, storyCount: 9 },
  { region: "Americas", level: "Moderate", score: 47, storyCount: 4 },
  { region: "Africa", level: "Moderate", score: 41, storyCount: 3 },
];

// Fresh story injection templates matching current themes (Iran-Israel, oil volatility, Ukraine, etc.)
export const storyTemplates: Omit<Article, 'id' | 'publishedAt'>[] = [
  {
    title: "US Completes Additional Strikes on Iranian Targets as Trump Issues New Deadline",
    summary: "American forces struck Iranian military sites overnight. President Trump said a deal must be reached within days or further action will follow.",
    body: "The United States conducted additional precision strikes against Iranian military infrastructure following Iran's missile response. President Trump stated publicly that the US will 'strike Iran very hard' if a deal is not reached quickly. Oil prices spiked on the news while equity futures turned volatile.",
    source: "CNBC",
    url: "https://www.cnbc.com/",
    category: "geopolitics",
    regions: ["Middle East", "Americas", "Global"],
    topics: ["Conflict Zones", "Defense & Security", "Energy & Oil"],
    impact: "High",
  },
  {
    title: "Oil Surges Past $106 as Fears Grow Over Prolonged Hormuz Disruption",
    summary: "Brent crude climbed above $106-$107 per barrel. Physical traders are paying large premiums for prompt delivery amid uncertainty over the Strait of Hormuz.",
    body: "Oil prices remain structurally elevated as the Iran conflict shows no quick resolution. Market participants are pricing in the risk of even partial disruption to the Strait of Hormuz. Several large energy traders have activated contingency plans for alternative supply routes.",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/",
    category: "markets",
    regions: ["Middle East", "Global"],
    topics: ["Energy & Oil", "Commodities"],
    impact: "High",
  },
  {
    title: "Ukraine Hits Major Russian Air Base and Refinery in Deepest Strike This Month",
    summary: "Long-range Ukrainian drones struck a key Russian bomber base and an oil facility deep inside the country. Russia launched retaliatory missile waves overnight.",
    body: "Ukrainian long-range strikes hit a strategic Russian air base used for bomber operations and a major refining complex. Moscow responded with one of its largest missile and drone salvos in weeks against Ukrainian energy and cities. European gas and defense stocks moved higher on the escalation.",
    source: "AP News",
    url: "https://apnews.com/",
    category: "geopolitics",
    regions: ["Europe", "Russia & Central Asia"],
    topics: ["Defense & Security", "Energy & Oil", "Conflict Zones"],
    impact: "High",
  },
  {
    title: "Gold Tests Fresh Highs Above $2,680 as Safe-Haven Buying Accelerates",
    summary: "Spot gold pushed toward new records. Central banks and ETF investors continue adding exposure amid the Middle East crisis and broader uncertainty.",
    body: "Gold is benefiting from a classic flight-to-safety bid as well as ongoing structural buying from central banks. The PBoC and several Gulf institutions have been active. Options markets show traders positioning for further upside if the Iran situation deteriorates.",
    source: "Reuters",
    url: "https://www.reuters.com/",
    category: "markets",
    regions: ["Global"],
    topics: ["Commodities", "Central Banks & Policy"],
    impact: "Medium",
  },
];
